# Generated by Django 4.2.7 on 2023-11-25 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bankaccount_remove_userprofile_is_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='customer_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='employee_profile',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user_profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='users.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user_profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='users.userprofile'),
            preserve_default=False,
        ),
    ]
