# Generated by Django 4.2.7 on 2023-11-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0002_remove_scratchpadrecord_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchpadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.customer')),
                ('employees', models.ManyToManyField(to='works.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Scratchpad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('records', models.ManyToManyField(to='scratchpads.scratchpadrecord')),
            ],
        ),
    ]
