# Generated by Django 4.2.7 on 2023-11-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scratchpadrecord',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='scratchpadrecord',
            name='employees',
        ),
        migrations.DeleteModel(
            name='Scratchpad',
        ),
        migrations.DeleteModel(
            name='ScratchpadRecord',
        ),
    ]
